### ISSUE TITLE
[Domain] 사용자 Member 및 members 테이블 정의

### ISSUE THREAD

**Issue by ttasjwi** [sungju-kim/sidedish#10]
## TODO
- [x] Member 테이블 DDL 작성
- [x] Member의 프로퍼티 추가(member_id, name(이름), 주소(도, 광역시 수준)
- [x] Member 클래스의 테스트 코드 작성
