### ISSUE TITLE
[Controller] 상품 상세 샘플 API 구현 

### ISSUE THREAD

**Issue by ttasjwi** [sungju-kim/sidedish#24]
## TODO
 - [x] "/items/{itemId}"로 요청 시 상품 목록을 응답해야함.
   - [x] ItemDetailResponse 클래스로 응답할 것
     - [x] 상품명
     - [x] 상품설명
     - [x] 상품원가
     - [x] 상품할인가
     - [x] 진행 중인 할인정책
     - [x] 적립금
     - [x] 새벽배송 지원여부
     - [x] 배송료
     - [x] 무료 배송시 최소 지불금
     - [x] 서버측 보유 수량
     - [x] 메인 이미지들
     - [x] 서브 이미지들
