### ISSUE TITLE
[Domain] 상품 이미지 ItemImage 클래스 작성

### ISSUE THREAD

**Issue by ttasjwi** [sungju-kim/sidedish#27]
## TODO
- [x] 상품 이미지 ItemImage 클래스 작성
  - [x]  상품-상품 이미지는 1:多 관계임. Item의 관계에서 주인이다.
- [x] 상품 이미지의 타입을 분류하기 위해 ItemType enum 정의

## 고찰
- 메인이미지와 서브이미지를 구분할 필요가 있음
