### ISSUE TITLE
[Feat] 상품 id로 상품 상세정보를 조회하는 기능 추가

### ISSUE THREAD

**Issue by ttasjwi** [sungju-kim/sidedish#31]
## TODO
- [ ] ItemService 클래스 생성
  - [ ] findOne : 상품 id로 repository에서 상품을 찾아다, responseDto로 응답
- [ ] ItemDetailResponse 수정 : 실제 Item 기반으로 생성하도록 함

---
