### ISSUE TITLE
[Feat] 특정 섹션에 속한 상품 목록 가져오는 기능 추가

### ISSUE THREAD

**Issue by ttasjwi** [sungju-kim/sidedish#32]
## TODO
- [ ] findBySection : 상품 섹션명으로 repository에서 상품을 찾아다, responseDto로 응답
- [ ] ItemListElement : 기존엔 더미데이터로 응답했었으나, 실제로 Item 기반으로 생성하도록 변경
- [ ] ItemListResponse : ItemElementDto를 감싼 클래스
