### ISSUE TITLE
[Feat] Item 클래스에 재고 감소 로직 추가

### ISSUE THREAD

**Issue by ttasjwi** [sungju-kim/sidedish#48]
---

## TODO
- [ ] Item 클래스에 재고를 감소시키는 로직 추가
  - [ ] 재고보다 많은 양을 감소시키려 시도하면 예외 발생
- [ ] 성공, 실패 테스트 코드 작성

---
